### ISSUE TITLE
Dehumidifier detected as AC unit

### ISSUE THREAD

**Issue by AdamCLarsen** [bm1549/home-assistant-frigidaire#11]
I saw the conversation about detecting type, however my unit is returning the NA SN with `KK`.

Not sure why that's happening.  Here is the result of the call to `user-appliance-reg/users/{{username}}/appliances?country=US&includeFields=true`

I have a Frigidaire FGAC7044U1E

```
{
    "status": "OK",
    "code": "ECP0000",
    "message": "success",
    "data": [
        {
            "appliance_type": "950133009_00",
            "appliance_id": "91806328-443E07019513",
            "pnc": "950133009",
            "elc": "00",
            "sn": "91800000",
            "mac": "443E07019513",
            "cpv": "00",
            "nickname": "Dehumidifier",
            "fields": {
                "NASerialNumber": "KK91800000"
            }
        }
    ]
}
```

As I don't have an Frigidaire AC, I worked around it by removing the check and only having the humidify defined.  I am posting here, if other have problems, you have more data to work with.

Also, it does detected correctly as a Dehumidifier in the Frigidaire app.

**Comment by gazpachoking** [comment]
Hmm. This is disappointing. Not sure the best method given this info. Perhaps the last 2/3 digits of PNC is better, and we can make a lookup table? We should probably make an error level log message that spits out the appliance object and instructions for people to post it with their model info if it's not one of our currently known models. The more different models with info we gather the better method we can create.

**Comment by ZachPL** [comment]
Just in case it matters in the future, this is the model that I am using that is detected correctly FGAC5044W1

**Comment by gazpachoking** [comment]
> FGAC5044W1

That's the same one I had, and it was the only dehumidifier data point we had until @AdamCLarsen's
