### ISSUE TITLE
Entities suddenly unavailable

### ISSUE THREAD

**Issue by rpitera** [bm1549/home-assistant-frigidaire#12]
Using 306ea32 with HA 2021.9.6 (details below).  A few days ago, my Frigidaire entities became unavailable after weeks (months) of working without incident.  They're working in the Android app and working/communicating in both the Alexa skill and Google Assistant, so I know they are 'online'.  They just suddenly stopped showing available in HA.  

Tried uninstalling/reinstalling the component (from the integrations section) and although the config flow works without error and detects my two AC units, they show as unavailable.  Adding debug to the logs via:

```
logger:
  default: critical
  logs:    
    custom_components.frigidaire: debug
    homeassistant.components.climate: debug

```
showed only a successful setup on the climate side:

`2021-09-13 10:23:04 INFO (MainThread) [homeassistant.components.climate] Setting up climate.frigidaire`

and no messages at all from the component.   Not sure what's wrong as it worked awesome from the first time I set it up until a few days ago and I'm not sure how to proceed with further debugging.  Open to suggestions on gathering more data that I might have missed.  No changes in my network and only changes to HA have been core updates.

NOTE: I have not tried removing and reinstalling from HACS yet, but will be glad to do so if you need the info.

## System Health

version | core-2021.9.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.61
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4207
Installed Version | 1.15.2
Stage | running
Available Repositories | 892
Installed Repositories | 66

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 16, 2021, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.3
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 30.8 GB
disk_used | 21.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.1.3), ADB - Android Debug Bridge (0.8.0), ESPHome (2021.8.2), Visual Studio Code (3.6.2), Let's Encrypt (4.11.0), Node-RED (10.0.0), Home Assistant Google Drive Backup (0.105.1), MariaDB (2.4.0), Check Home Assistant configuration (3.8.0), Glances (0.13.0), Vaultwarden (Bitwarden) (0.13.0), Portainer (2.0.0), Tautulli (2.3.0), phpMyAdmin (0.5.0), php-nginx Docker Image (latest), rest980 Docker Image (20200205), ioBroker (0.8.0), eufy_security_addon (0.3.3), ozwcp (1.1.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 50
views | 28
mode | storage

</details>

**Comment by fiveball02** [comment]
I am having the same problems.  My setup is identical to yours.  I did install HACS fresh today also, but it did not make a difference.

**Comment by attempted** [comment]
I actually just opened a duplicate issue on this. If you use the the `frigidare` folder from this commit it still works: 84a91c585f6bd89171c2d0be3b1f30d3c2d19f50

**Comment by rpitera** [comment]
Just going to cross ref them both then.  #13
