### ISSUE TITLE
Most Recent Commit (09/05/2021) causing AC to be "Unavailable"

### ISSUE THREAD

**Issue by glnces** [bm1549/home-assistant-frigidaire#13]
Hey there! After installing this integration and playing around I found that the most recent commit 306ea32ee59fc0aef4fa9f7e7d889b0e5e76b9e0 will discover my AC units, but will list them as "Unavailable" in Home Assistant. I instead checked out an earlier commit 84a91c585f6bd89171c2d0be3b1f30d3c2d19f50 and it's working fine. Just wanted to give a heads up.

**Comment by bm1549** [comment]
@attempted I'm not near my laptop, but if you can put up a fix in a PR I'd be happy to approve/merge it!

**Comment by gazpachoking** [comment]
Sorry guys, I probably messed the unavailable stuff up. I'll take a peek
unless someone gets to it first.

**Comment by fiveball02** [comment]
Just cloned the repo and can confirm that it is working correctly now.  Thanks.

**Comment by bm1549** [comment]
Fixed in #14
