### ISSUE TITLE
Add hacs.json for easier install in home assistant using the community store. 

### ISSUE THREAD

**Issue by cpyarger** [bm1549/home-assistant-frigidaire#2]
You can already install this using custom repositories. but adding a hacs.json file helps with the integration a bit
an example hacs.json is as follows
```json
{
  "domains": ["climate"],
  "name": "Home Assistant Frigidaire Integration",
  "render_readme": true,
  "homeassistant": "0.96.0"
}
```

**Comment by bm1549** [comment]
@cpyarger I think I did this properly, but I don't have hacs to test it. Let me know if this works!

**Comment by cpyarger** [comment]
I made a change and sent a pull request

Warmest Regards,


Christopher P. Yarger

Phone: 802-505-7574
Skype: cpyarger

/************************************
Based upon email reliability concerns,
please send an acknowledgment in response to this note.
