### ISSUE TITLE
`hvac_action` property missing from `FrigidaireClimate` class

### ISSUE THREAD

**Issue by thejevans** [bm1549/home-assistant-frigidaire#21]
This would potentially close #6. [ecobee component implementation](https://github.com/home-assistant/core/blob/3e3f7ea99590ead08bfd9d2a7de032644b830e4e/homeassistant/components/ecobee/climate.py#L503) for reference. This should be fairly easy to add.

**Comment by thejevans** [comment]
I have implemented the function in [thejevans/home-assistant-frigidaire:hvac-action](https://github.com/thejevans/home-assistant-frigidaire/tree/hvac_action), but I need someone with a Frigidaire AC unit to test it.

**Comment by SvenPaterson** [comment]
I have a window unit, just connected it today. Saw this repo and happy to help in any way I can. FHWW063WB1 window unit, fully up to date on firmware as of 3/10/23. Currently integrating it into my HA tonight.

**Comment by SvenPaterson** [comment]
> I have implemented the function in [thejevans/home-assistant-frigidaire:hvac-action](https://github.com/thejevans/home-assistant-frigidaire/tree/hvac_action), but I need someone with a Frigidaire AC unit to test it.

I have this branch running with my window unit just fine. Are there any specific actions you want tested beyond basic functionality?
