### ISSUE TITLE
Uses "frigidaire" package which always connect to LATAM Region - Should use "pyelectroluxconnect" Instead

### ISSUE THREAD

**Issue by indomitableMan** [bm1549/home-assistant-frigidaire#27]
This code has a couple of issues related to connecting to Electrolux which owns the Frigidaire brand:

In the manifest.json file there is a hard coded dependency - "frigidaire==0.18.11" that should be changed to "frigidaire>=0.18.11" since the current version of the "frigidaire" package is 0.18.12. Without this change, the integration will not bring up the configuration screen asking for the username and password to connect to the Frigidaire API.

An even bigger issue that this the "frigidaire" package always connects to the same API URL (https://api.latam.ecp.electrolux.com) which is for the Latin America region. Electrolux runs API servers in multiple regions of the world and each has a unique URL. The Python package "pyelectroluxconnect" takes this into consideration and provides a "region" parameter which can be set during the initial connection to the Electrolux API server.

I would respectfully suggest changing out the "frigidaire" package for the "pyelectroluxconnect" connect package since it appears to be more fully featured and functional across different regions.

**Comment by indomitableMan** [comment]
created a separate fork with updates to const.py to support eventual migration to pyelectroluxconnect package.

**Comment by bm1549** [comment]
I'm happy to accept a PR if you're willing to make the required updates!
