### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by jazzmonger** [bm1549/home-assistant-frigidaire#29]
I get this whenever I try and reload the integration
ha 2023.05.01
supervised on Debian - fully supported install

Logger: homeassistant.config_entries
Source: custom_components/frigidaire/__init__.py:23
Integration: frigidaire
First occurred: 10:30:55 PM (1 occurrences)
Last logged: 10:30:55 PM
Error setting up entry frigidaire for frigidaire

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/frigidaire/__init__.py", line 23, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by boctok** [comment]
You have to download the updated repo (3 weeks ago), copy it into the custom_components directory, overwriting the old files.
Then, you have to go into configuration, devices & services and delete the old Frigidaire integration.
IMPORTANT - restart Home Assistant, other5wise, you'll simply reinstall the old integration that was in the cache.
After HA has restarted, reinstall the Frigidaire integration and supply your username and password. You shouldn't have to do anything else, unless you named your appliance something else.

**Comment by bm1549** [comment]
Please follow @boctok's steps here!

**Comment by jazzmonger** [comment]
That worked!  Thanks.
