### ISSUE TITLE
Depreciated call to async_setup_platforms() in __init__.py

### ISSUE THREAD

**Issue by fouram** [bm1549/home-assistant-frigidaire#30]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: May 7, 2023 at 11:12:14 PM (1 occurrences)
Last logged: May 7, 2023 at 11:12:14 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for frigidaire using this method at custom_components/frigidaire/__init__.py, line 32: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by bm1549** [comment]
Please follow the steps in #29
