### ISSUE TITLE
Frigidaire login component no longer working

### ISSUE THREAD

**Issue by ha-elguano** [bm1549/home-assistant-frigidaire#35]
For a few weeks now, I'm no longer able to login to the Frigidaire server through this integration. 

Whenever I enter my username and password, I immediately get a "Failed to Connect" error.

I've verified that the username and password login correctly in the Frigidaire 2.0 app and on the Frigidaire.com servers.

**Comment by bm1549** [comment]
@ha-elguano Have you updated to the latest version of this component?

**Comment by ha-elguano** [comment]
Oh indeed, the new change to manifest.json did the trick, for some reason I didn't see the update earlier. Thank you!
