### ISSUE TITLE
Dehumidifier is no longer being provided b the frigidaire integration

### ISSUE THREAD

**Issue by StevenBrehmer** [bm1549/home-assistant-frigidaire#37]
Good Afternoon, 

I just added this integration  - which worked perfectly to identify what Frigidaire devices are on my network. Unfortunately once I added the integration and my dehumidifier popped up - I received this warning

"This entity is no longer being provided by the frigidaire integration. If the entity is no longer in use, delete it in settings."

I left it for about an hour to see if it just took some time to receive info/controls from the dehumidifier, but the dehumidifier entity remains as unavailable. 

I will mention - I noticed I needed to install a new frigidaire app recently - wondering if this integration only uses the previous version of the app?

**Comment by bm1549** [comment]
Can you confirm that you are on the latest version of the integration?

**Comment by StevenBrehmer** [comment]
Yes - I downloaded from the files

**Comment by StevenBrehmer** [comment]
Sorry - did not mean to close - fat fingered

**Comment by Conundrum1911** [comment]
Same experience here.  Had issues a month ago and needed the new version of this plug-in/add-on, which worked.

I then installed the new app on my iPhone and added the dehumidifier, and noticed this plugin no longer saw my dehumidifier.  I then reinstalled the old iPhone app, removed the dehumidifier from both new and old, and added it only to new.  Now then I check either the old iPhone app or the Home Assistant plugin, it says no devices found after logging in.

Maybe after the first change that broke this program, Frigidaire moved something else and store their "new" devices differently?

**Comment by bm1549** [comment]
Unfortunately I only have air conditioners and not dehumidifiers so I'm unable to test or reproduce this

Frigidaire has changed a lot of things on their end without any rhyme or reason, so a change on their side is the likely culprit

**Comment by ZachPL** [comment]
Mine is still working

**Comment by miles267** [comment]
Hi - can someone please point me to instructions on how to install this integration within HA?  I actually want to use it with my dehumidifer 😄
