### ISSUE TITLE
Connection Errors

### ISSUE THREAD

**Issue by jhemak** [bm1549/home-assistant-frigidaire#43]
Anyone seeing connection errors the past 1-2 days where it was previously working?

**Comment by ha-elguano** [comment]
Yep, see "Failed to set up" and reloading/rebooting doesn't help.

**Comment by sirjmann92** [comment]
Same issue here. Couldn't even log into the app on my Android phone. Uninstalled it then went to the Play store and reinstalled it. There's a new version. I'm able to log into the app now but the HA integration still doesn't work. I'm guessing Frigidaire changed something again...

**Comment by jhemak** [comment]
@bm1549 - this can be closed based on your recent changes.  However, in addition to the fan and compressor status being gone, I also noticed the bin_full attribute is now always false even want the tank is in fact full.  Just wanted to make you aware, not sure there's anything you can do about it.
