### ISSUE TITLE
Changing Fan Speed Error 

### ISSUE THREAD

**Issue by aphorism9** [bm1549/home-assistant-frigidaire#51]
I am using a fhww082wce model a/c unit and integrated the unit into Home Assistant. All works well aside from the following error received when trying to adjust the fan speed settings:

`Failed to call service climate/set_fan_mode. type object 'Setting has no attribute 'FAN_SPEED_SETTING'`

Any advice on how to fix this error would be very much appreciated!

EDIT: here is the log: 

2024/02/13 20:51:37 | stdout | AttributeError: type object 'Setting' has no attribute 'FAN_SPEED_SETTING'[0m
-- | -- | --
2024/02/13 20:51:37 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^
2024/02/13 20:51:37 | stdout | return [Component(Setting.FAN_SPEED_SETTING, fan_speed)]
2024/02/13 20:51:37 | stdout | File "/usr/local/lib/python3.12/site-packages/frigidaire/__init__.py", line 145, in set_fan_speed
2024/02/13 20:51:37 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/02/13 20:51:37 | stdout | action = frigidaire.Action.set_fan_speed(HA_TO_FRIGIDAIRE_FAN_MODE[fan_mode])
2024/02/13 20:51:37 | stdout | File "/config/custom_components/frigidaire/climate.py", line 242, in set_fan_mode

**Comment by rothn** [comment]
Is this still reproducible?

**Comment by aphorism9** [comment]
I lost faith in the integration as the files updated live in a “temporary” folder that resets each time home assistant does, which was extremely annoying.I’m sure there’s a way around this, but this was my barrier!Other than that, the integration did function very well.Sent from my iPhoneOn Aug 31, 2024, at 12:02 AM, Nicholas Roth ***@***.***> wrote:﻿
Is this still reproducible?
