### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by marty22877** [bm1549/home-assistant-frigidaire#53]
I've used this integration for the past couple of years for my window AC units.  I just installed my window AC units today and noticed my HA integration stopped working.  I deleted the old files, reuploaded the new ones and tried to connect.  I'm getting an Unexpected error.  I've also noticed that if I change my password in the app, I only get a code in an email to log in.  My login does work on the frigidaire website to log into my account.  Here are the logs:

This error originated from a custom integration.

Logger: custom_components.frigidaire.config_flow
Source: custom_components/frigidaire/config_flow.py:66
integration: frigidaire
First occurred: 10:05:25 AM (1 occurrences)
Last logged: 10:05:25 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/frigidaire/config_flow.py", line 66, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/frigidaire/config_flow.py", line 38, in validate_input
    appliances = await hass.async_add_executor_job(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frigidaire/config_flow.py", line 31, in setup
    return client.get_appliances()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/frigidaire/__init__.py", line 417, in get_appliances
    return get_appliances_inner()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/frigidaire/__init__.py", line 414, in get_appliances_inner
    return list(map(generate_appliance, appliances))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/frigidaire/__init__.py", line 403, in generate_appliance
    return Appliance(raw_appliance)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/frigidaire/__init__.py", line 106, in __init__
    self.appliance_type: str = args['properties']['reported']['applianceInfo']['applianceType']
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'applianceInfo'

**Comment by Waank1** [comment]
I am having the same issue.  Can log in with Frigidaire app so user and pass are correct.

Running:
Core 2024.6.0
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240605.0

Here is a copy of the error log:

This error originated from a custom integration.

Logger: root
Source: custom_components/frigidaire/config_flow.py:30
integration: frigidaire
First occurred: 21:59:17 (6 occurrences)
Last logged: 22:08:03

```
This error originated from a custom integration.

Logger: root
Source: custom_components/frigidaire/config_flow.py:30
integration: frigidaire
First occurred: 21:59:17 (6 occurrences)
Last logged: 22:08:03

Request failed with status 400: b'{"error":"cas_4400","message":"Bad request received","detail":"Some query parameter has invalid value or invalid combination of parameters has been provided"}'

Error processing request: GET https://api.ocp.electrolux.one/one-account-user/api/v1/identity-providers?brand=frigidaire&email=waank1&loginType=OTP headers={'x-api-key': 'UcGF9pmUMKUqBL6qcQvTu4K4WBmQ5KJqJXprCTdc', 'Authorization': 'Bearer eyJraWQiOiIxMGZhMWQwOWY4YjM2OGFjYmE4YmRiNDYxOTFmZmVhODE1MmZiM2YzZjQ5N2RhZjk1OWFjNWIzNDM5ZDI3OGY0IiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE3MTc3MjkxNTcsImlzcyI6Imh0dHBzOi8vYXBpLm9jcC5lbGVjdHJvbHV4Lm9uZS9vbmUtYWNjb3VudC1hdXRob3JpemF0aW9uIiwiYXVkIjoiaHR0cHM6Ly9hcGkub2NwLmVsZWN0cm9sdXgub25lIiwiZXhwIjoxNzE3NzcyMzU3LCJzdWIiOiJGcmlnaWRhaXJlT25lQXBwIiwiYXpwIjoiRnJpZ2lkYWlyZU9uZUFwcCIsInNjb3BlIjoiIiwib2NjIjpudWxsfQ.dkaQjZk1-Nb7S7no_B7sOcxwwsNEkPay3kbh_FbIqdGWFtnpDOUJgFIYG3Ja7qMu1M4F3Af7QiGJGltYAE39rdD7S1Onpc3Oa0qOq4V6TusYLXqEhMQUKtJKpqoHTjE7--gHSePOqR47JzP4Z0Jji_QBazmXZkdjoGjGhORssEQOieT8W0sckO34wVxVtT61kMcYR0XLlr5kjsDQfV_FEoGZm_RxTY3umjanK29n3laLzFuBuHpUxZV0MjgEbs_1dX9JVJCN57C_K7lFcbm1aF4_ta0QC8J0yo1IDg60YTvKA67GPkKiXRMP5nCV5cOh7SmeVqY546yILtfwWRg9Mw', 'Accept': 'application/json', 'Accept-Charset': 'UTF-8', 'User-Agent': 'Ktor client'} payload=

Error processing request: GET https://api.ocp.electrolux.one/one-account-user/api/v1/identity-providers?brand=frigidaire&email=waank1&loginType=OTP headers={'x-api-key': 'UcGF9pmUMKUqBL6qcQvTu4K4WBmQ5KJqJXprCTdc', 'Authorization': 'Bearer eyJraWQiOiIxMGZhMWQwOWY4YjM2OGFjYmE4YmRiNDYxOTFmZmVhODE1MmZiM2YzZjQ5N2RhZjk1OWFjNWIzNDM5ZDI3OGY0IiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE3MTc3Mjk2NTAsImlzcyI6Imh0dHBzOi8vYXBpLm9jcC5lbGVjdHJvbHV4Lm9uZS9vbmUtYWNjb3VudC1hdXRob3JpemF0aW9uIiwiYXVkIjoiaHR0cHM6Ly9hcGkub2NwLmVsZWN0cm9sdXgub25lIiwiZXhwIjoxNzE3NzcyODUwLCJzdWIiOiJGcmlnaWRhaXJlT25lQXBwIiwiYXpwIjoiRnJpZ2lkYWlyZU9uZUFwcCIsInNjb3BlIjoiIiwib2NjIjpudWxsfQ.gSgVzirUhLAv4ENo4VeAmziE9eflKj04Ohh2JOJnLCDS_RLey8r3D3SnZPdavHjFaEGsizCpKoy94asVREbYbkZ9LqOZktCAdszyYLBmr-IyQVAY6zqM_k5bOpSrqNigdOdMog_QdCl8B1YbujrEHe5W7CZqc-pII8d4O67T_bXZPaHfKmMqW3jpOTXSgL5kR-tIImTKBB_wdA8DIST7C8XNsqRIe3FNmp3pD7CM9Kto3Id3DIjf7amTI_XmOZCeZKXKbaj_gbK69VaS9G8NkcTXYT_2r5eIcqCl7qtu37-7vYCgPdbxOYEvKw7Kmulz-m8K3YV5E639py5Vnj1JjQ', 'Accept': 'application/json', 'Accept-Charset': 'UTF-8', 'User-Agent': 'Ktor client'} payload=

Error processing request: GET https://api.ocp.electrolux.one/one-account-user/api/v1/identity-providers?brand=frigidaire&email=waank1&loginType=OTP headers={'x-api-key': 'UcGF9pmUMKUqBL6qcQvTu4K4WBmQ5KJqJXprCTdc', 'Authorization': 'Bearer eyJraWQiOiIxMGZhMWQwOWY4YjM2OGFjYmE4YmRiNDYxOTFmZmVhODE1MmZiM2YzZjQ5N2RhZjk1OWFjNWIzNDM5ZDI3OGY0IiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE3MTc3Mjk2ODIsImlzcyI6Imh0dHBzOi8vYXBpLm9jcC5lbGVjdHJvbHV4Lm9uZS9vbmUtYWNjb3VudC1hdXRob3JpemF0aW9uIiwiYXVkIjoiaHR0cHM6Ly9hcGkub2NwLmVsZWN0cm9sdXgub25lIiwiZXhwIjoxNzE3NzcyODgyLCJzdWIiOiJGcmlnaWRhaXJlT25lQXBwIiwiYXpwIjoiRnJpZ2lkYWlyZU9uZUFwcCIsInNjb3BlIjoiIiwib2NjIjpudWxsfQ.VMeaERGIVJIkC8M_VUuyCeMYDAj67iQB_W4hqSkD6LwM1Zo-BEvwArobPYd6t82CqRMTEdMd_DyXsjHJkgliuE1hmLtLe_Zuo8t9UN3NvNGaeTEYddzfJO79EErtprWdo7cYwxIxSRNMQTBZTySku-iJEvEQblsDSFelORiHC51GPJsv76SGiPIGQGZvxxIMHL_YvXc9CWL2fJzui-t1z0T6pNwYhXikdSftZ0UXO841gBZwGslD7y15hbse4T-S-Rw-qzOFYcTqiKlIXvZdfusOaEyNkVKm2m0n3FtWEU_iwBQznwmqoQY9AxhEGbqV18vlQFwCFLZysnaUCHFkcQ', 'Accept': 'application/json', 'Accept-Charset': 'UTF-8', 'User-Agent': 'Ktor client'} payload=
```
Thanks,
Russ
