### ISSUE TITLE
hvac_action attribute disappeared

### ISSUE THREAD

**Issue by amaisano** [bm1549/home-assistant-frigidaire#55]
Between last summer and this summer, the `hvac_action` (idle, cooling, etc) attribute is completely gone from the climate entities.

Where did it go? Can we get it back please? I have lots of automations dependent on whether my units are idle or not...

Thanks.

Attributes from a "normal" air conditioner I have (not Frigidaire):

```
hvac_modes: auto, cool, fan_only, off
min_temp: 16
max_temp: 29
target_temp_step: 1
fan_modes: auto, high, low, medium
current_temperature: 24
temperature: 20
current_humidity: 64.9
fan_mode: auto
hvac_action: idle
friendly_name: Sunroom AC
supported_features: 9
```

Attributes now from Frigidaire - missing `hvac_action` and I think other items may have changed, too:

```
hvac_modes: off, cool, auto, fan_only
min_temp: 15.6
max_temp: 32.2
target_temp_step: 1
fan_modes: auto, low, medium, high
current_temperature: 26.7
temperature: 25
fan_mode: auto
check_filter: false
assumed_state: true
friendly_name: Office AC
supported_features: 393
```

**Comment by amaisano** [comment]
@bm1549 any chance of this value coming back? Or am I going to have to put a power monitoring plug on the thing?

**Comment by bm1549** [comment]
@amaisano 

Thanks for the suggestion! We don't have the resources to implement this now, but we'd love to see your contribution. Feel free to submit a pull request, and we'll review it.

**Comment by amaisano** [comment]
But... it was there before. It's a regression.

**Comment by rothn** [comment]
There was a major API change between last summer and this summer, in which Frigidaire removed some more low-level details that were returned by their API. The entire backend had to be rewritten. It's not surprising that some things changed. Feel free to test out https://github.com/bm1549/frigidaire/tree/main directly in Colab and see if the information is present in the API to determine when the device is idle (you should be able to make raw API calls from that library in addition to the high-level functions it exposes). Let us know what you find!

**Comment by bm1549** [comment]
FWIW I tried running my device in Eco mode and couldn't find any fields that change when the compressor turns on/off so this may not be possible anymore

There is a field in the response `applianceState`, but it returns `'RUNNING'` whether the device is cooling or not, which isn't helpful. Same thing with `fanSpeedState` always showing the prior state eg. `MIDDLE`

**Comment by bm1549** [comment]
Closing this as the field no longer exists after Frigidaire's latest update
