### ISSUE TITLE
"Failed to connect"

### ISSUE THREAD

**Issue by corgana** [bm1549/home-assistant-frigidaire#69]
Not much to say, I enter username and password and get a simple "Failed to connect" error. This was working fine a few days ago.

**Comment by amaisano** [comment]
Same. Getting a 503 response for most API calls suddenly.

The native Frigidaire app is for too ("Something went wrong") so it's likely a full outage.

**Comment by corgana** [comment]
The app was actually working for me when I made this post but it's not now. Good call I'm sure it's just that.

**Comment by Clutch57** [comment]
Looks like the integration went unavailable at 6pm est.  Oem app on phone looked like it was working until I tried to change a setting .

**Comment by rothn** [comment]
I'm getting `frigidaire.FrigidaireException: Request failed with status 429`... but my app works. Weird-- this is my first time getting that error without messing around with the API manually and creating a bunch of sessions. I wonder if our integration retried too many times during the outage.

**Comment by Clutch57** [comment]
Appears to be working again.

**Comment by corgana** [comment]
Yes looks like it was on Frigidaire's end. Closing this.
