### ISSUE TITLE
AC reporting as OFF despite being on

### ISSUE THREAD

**Issue by joewesch** [bm1549/home-assistant-frigidaire#75]
I have an automation that triggers each night to turn my AC on and then checks after 5 minutes if it was successful. For the past 2 nights (last night and tonight) it has notified me that it wasn't successful, but when I went to go check on the unit it was running just fine.

I cloned down your python library and it seems the API response does report the unit as off:

```
In [7]: f.get_appliance_details(a)
Out[7]: 
{'sleepMode': 'OFF',
 'cleanAirMode': 'OFF',
 'applianceInfo': {'applianceType': 'AC'},
 'temperatureRepresentation': 'FAHRENHEIT',
 'schedulerMode': 'OFF',
 'targetTemperatureF': 69.0,
 'targetTemperatureC': 20.555555555555557,
 'schedulerEventCount': 0,
 'applianceState': 'OFF',
 'FilterState': 'CHANGE',
 'mode': 'OFF',
 'alerts': [],
 'ambientTemperatureF': 77.0,
 'filterState': 'CHANGE',
 'fanSpeedSetting': 'AUTO',
 'networkInterface': {'swVersion': 'PW1RS420_210422f',
  'linkQualityIndicator': 'VERY_POOR'},
 'fanSpeedState': 'MIDDLE',
 'ambientTemperatureC': 25.0,
 'connectivityState': 'connected'}
```

So, it sounds like the API is returning incorrect information. I understand it's probably not something you can fix, but just figured I would report it.

**Comment by joewesch** [comment]
I should add, that it seems that at some point during the night last night it did report that it was on COOL mode:

> Bedroom AC changed to Cool
3:37:12 AM - 18 hours ago

**Comment by bm1549** [comment]
@joewesch I've always been aware of the delays, but I've admittedly never tracked how long the delays take

To workaround the delays, I've configured my device with assumed_state and it's worked well for me in practice - https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/#classifiers

**Comment by joewesch** [comment]
Yup, this seems quite a bit worse. The 5 minute pause that I put in my automation has been more than enough to account for the delay up until now. It just seems like recently the API response is just broken. I just checked and now it's showing as unavailable for 2 hours so maybe they are having issues.

**Comment by bm1549** [comment]
Do you also have the Frigidaire app? I'm curious if you notice different behavior if you check the state in the app/try turning it on there

That'd rule out any client-side problems and guarantee backend issues

**Comment by joewesch** [comment]
The app says it's offline as well right now. The next time there is a discrepancy I'll check.

**Comment by joewesch** [comment]
Whelp, I think they finally killed off the model I was using. I went to do a factory reset on my unit to see if that would fix it and got this error:

![Screenshot_20240928-070810](https://github.com/user-attachments/assets/13c56677-5c97-4dfc-84ee-f81118212f09)

I'm going to close this issue as it has nothing to do with your integration. Thanks for a solid integration, I've been using it since the beginning pretty much.

**Comment by bm1549** [comment]
That's pretty terrible. I actually have the same model, but I've already taken it down for the fall so haven't experienced this yet

Are they offering you compensation or anything for your this?

**Comment by joewesch** [comment]
I got this email back in June:

>To our valued consumer,
> 
> Our records show that you own a connected Frigidaire Window Air Conditioner. We have recently made industry-standard security updates to our connected products, and as a result, you will find that your Air Conditioner no longer connects with our Frigidaire App. While we strive to provide an excellent consumer experience for the entirety of your ownership, we recognize that losing the connected capabilities is both frustrating and disruptive. You will still be able to use your Window Air Conditioner as intended. As part of our commitment to providing a quality consumer experience, we will send you a Virtual MasterCard which you may use towards a replacement unit or as you wish.  
>
> Within the next 2-3 weeks, you will receive an email from [donotreply@mail.mypaymentvault.com](mailto:donotreply@mail.mypaymentvault.com). This email will contain the link where you can redeem your gift card. You will receive $20 for every impacted model that is registered to your account. Below is a list of impacted models.  
>
> Impacted Models 
FFRC0833R1 
FGRC0844S1 
FGRC1044T1 
FGRC1244T1 
>  
> If you have any questions, please contact our Customer Support at (800) 311-4667. 
>
> Thank you for being a valued member of our Frigidaire family, and we look forward to serving you better.  
>
> Sincerely, 
Electrolux Group

And, of course that $20 never actually materialized. I called and complained shortly after I received the email and said that I would no longer be able to set a schedule anymore so I wouldn't be able to use it "as intended". They didn't seem to care. They kept repeating the same thing that there was nothing they could do.

I still need to call and complain I never got my $20, but I'm definitely not buying another Frigidaire now.
